# Generated by Django 4.0.2 on 2022-03-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_user_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='logo_sucursal', verbose_name='img_perfil'),
        ),
    ]
